server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://47.103.31.116:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Yangnan@112200
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mybatis:
    mapper-locations: classpath*:mapper/*.xml
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

expire:
  validate.code: 60
  login.user: 3600